<script src="{{ asset('admin/js/tabler.min.js') }}"></script>
<script src="{{ asset('admin/js/my-js.js') }}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js"></script>
<script src="https://unpkg.com/filepond@^4/dist/filepond.js"></script>
<script src="{{ asset('admin/js/jquery.nestable.min.js') }}"></script>
{{-- <script src="{{ asset('admin/js/tinymce/js/tinymce/tinymce.min.js') }}"></script> --}}
<script src="https://cdn.tiny.cloud/1/ecwfburecpuvmfo31opy91x2cl616jaxyrx4vtheo012fd97/tinymce/7/tinymce.min.js"
    referrerpolicy="origin"></script>
